export const URLS = {
  base: process.env.REACT_APP_API_URL,
  post_article: "/article/media",
  get_article: "/article",
  commentDecoration: "/comment_decoration",
  commentImmobilier: "/comment_immobilier",
  post_decoration: "/decoration/media",
  get_decoration: "/decoration",
  post_immobilier: "/immobilier/media",
  get_immobilier: "/immobilier",
  media: "/media",
  pack: "/pack",
  packPrestation: "/packPrestation",
  personne: "/personne",
  professionnel: "/professionnel",
  prestation: "/prestation",
  projet: "/projet",
  clientProjet: "/client_projet",
  clientImmobilier: "/client_immobilier",
};
